version '3.1'

services:
  api_nest:
    image: postgres:15.1
    container: api_nest
    restart: always
    environment:
      POSTGRES_DB: api_nest
      POSTGRES_USER: secret
      POSTGRES_PASSWORD: secret
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432